opencv: Autospec creation for update from version 4.7.0 to version 4.8.1
Abduragim (1):
      minor grammatical fixes to dnn_custom_layers.md

Abduragim Shtanchaev (7):
      Merge pull request #23501 from Abdurrahheem:additional_lstm_tests
      Merge pull request #23475 from Abdurrahheem:lstm_fix_initialization
      added test for lstm without hidden
      Merge pull request #23614 from Abdurrahheem:lstm_layout_attribute
      add assert to check if layer input size is not empty
      added index that check all inputs of nodes that
      Merge pull request #23746 from Abdurrahheem:ash/graph_simplifier

Akshat Chauhan (1):
      Merge pull request #23662 from akormous:docfix

Alessandro de Oliveira Faria (A.K.A. CABELO) (1):
      ADD weights  yolov4-tiny in models.yml

Alex (8):
      Fix Heap-buffer-overflow READ in opj_jp2_apply_pclr
      add py charuco sample+choriginal.jpg+camera_params
      fix assert, add test
      fix test
      fix_warnings_quirc
      fix charuco matchImagePoints
      fix cornerRefinementMethod binding
      added graphicalCodeDetector, remove QRCodeDetectorBase

Alexander Alekhin (12):
      copyright: 2023
      copyright: 2023
      copyright: 2023 (update)
      videoio(test): skip unstable Media.audio test
      build: eliminate GCC9 warning from sift.simd.hpp
      perf: drop runtime time adjustment calibration
      test: reproducible results, enabled 2-channel tests, increased some thresholds
      dnn(tflite): add 3rdparty flatbuffers with pre-generated schema
      dnn(tflite): fix wrong axis normalization
      core(simd): 64-bit integer EQ/NE without misused 64F guard
      build(ios): disable workaround for CMake 3.25.1+
      gapi: fix static build with openvino

Alexander Duda (1):
      core: improve doc for setNumThreads

Alexander Panov (3):
      Merge pull request #23264 from AleksandrPanov:add_detect_qr_with_aruco
      Merge pull request #23848 from AleksandrPanov:fix_detectDiamonds_api
      Merge pull request #23647 from AleksandrPanov:fix_charuco_board_detect

Alexander Smorkalov (35):
      Supressed tones of Wdeprecated-copy that jump out of GTes after XCode update to 13.1 on Mac M1.
      Warning supression fix for XCode 13.1 and newer. Backport #23203
      Presume original book, update references.
      Added reference to Media Foundation.
      Extended setNumThreads documentation according to code review.
      Restored Java bindings for CPU features management.
      Build warning fix on Windows for Eigen wrapper.
      Fixed mask handling in AffineFeature.
      Added check that YUYV input of cvtColor has even width.
      OpenJPEG 2000 update to version 2.5.0
      Backport 5.x: Support for module names that start from digit in ObjC bindings generator.
      Added final constrants check to solveLP to filter out flating-point numeric issues.
      Re-integrated OpenJPEG 2.5.0 to OpenCV.
      Fixed FPS computation on some videos for FFmpeg backend.
      Fixed OpenJPEG 2000 compiler warning for some GCC versions (#23710).
      Python package classifiers sync with OpenCV-Python repo.
      Fixed potential buffer overflow of user file name in create_samples_app
      Refreshed JavaScript bindings for Aruco related algorithms.
      JS bingings fix for QR code detector.
      Added Aruco-based QR code detection method to python sample.
      JS bindings for Aruco-based QR code detector.
      JS bindings for bar code detector.
      Fixed barcode to be built without DNN
      Force mat_wrapper import to satisfy dependencies for MatLike alias.
      pre: OpenCV 3.4.20 (version++)
      pre: OpenCV 4.8.0 (version++)
      Document parameters of multi-dimentional reshape.
      FFmpeg wrapper update to FFmpeg version 3.4.13.
      FFmpeg/4.x: update FFmpeg wrapper 2023.6
      Git rid of unsafe raw pointers to Mat object.
      Reworked calibrate.py
      Release OpenCV 4.8.0
      CI update for 4.8.x branch.
      Use proper branch for CI pipelines.
      Version update to 4.8.1.

Alexey Shtern (1):
      Merge pull request #23301 from shtern:fix_quaternion

Anatoliy Talamanov (8):
      Merge pull request #23211 from TolyaTalamanov:at/pipeline-modeling-tool-perf-alignment
      Merge pull request #23595 from TolyaTalamanov:at/implement-openvino-backend
      Merge pull request #23766 from TolyaTalamanov:at/segmentation-demo-desync
      Merge pull request #23786 from TolyaTalamanov:at/expose-preprocessing-to-ie-backend
      Merge pull request #23796 from TolyaTalamanov:at/align-ie-backend-with-latest-openvino
      Merge pull request #23799 from TolyaTalamanov:at/ov20-backend-implement-missing-kernels
      Merge pull request #23843 from TolyaTalamanov:at/fix-missing-opaque-kind-for-kernel
      Merge pull request #23884 from TolyaTalamanov:at/fix-async-infer-ov-backend

Anna Khakimova (2):
      Fix tolerance for Preproc4lpiTest set
      Merge pull request #21797 from anna-khakimova:ak/merge3_extend_supported_types

Anna Petrovicheva (2):
      Create FUNDING.yml
      Update FUNDING.yml

Avasam (1):
      Merge pull request #23538 from Avasam:patch-1

Bhavit Patel (1):
      Merge pull request #23305 from bhavitp:fix/calib3d/undistortion_grid

CSBVision (2):
      Fixes #23187 (part 1)
      Add ENABLE_DELAYLOAD option

Christian Henkel (1):
      two typos

Christine Poerschke (4):
      Merge pull request #23612 from cpoerschke:3.4-issue-21532
      Merge pull request #23698 from cpoerschke:4.x-pr-21959-perf
      Merge pull request #23688 from cpoerschke:4.x-pr-21959-prep
      imgproc: optimise local cost computation in IntelligentScissorsMB::buildMap

Christoph Rackwitz (1):
      Merge pull request #23108 from crackwitz:issue-23107

Corentin Noël (2):
      highgui: Set hard GLib requirement to >=2.32
      highgui: Reduce the difference between GTK+2 and GTK+3 version

Damiano Falcioni (1):
      Merge pull request #23785 from damianofalcioni:4.x

Dmitry Kurtaev (18):
      Merge pull request #23161 from dkurt:dnn_tflite
      Merge pull request #23325 from dkurt:dnn_input_info
      Several fixes for ONNX importer: Expand, Gather
      Merge pull request #23409 from dkurt:dnn_tflite_quant
      Update FlatBuffers source code to 23.5.9
      Merge pull request #23604 from dkurt:dnn_no_protobuf
      Fix Region layer with OpenVINO in case of different width/height
      Merge pull request #23634 from dkurt:fix_nearest_exact
      Merge pull request #23674 from dkurt:py_cv_maketype
      Merge pull request #23679 from dkurt:py_cv_type_macro
      Fix mask thresholding
      Merge pull request #23691 from dkurt:pycv_float16_fixes
      Change Scalar assignment in Python from single value
      Consider half pixel mode in ONNX resize
      Replace CV_Assert_N
      Merge pull request #23754 from dkurt:remap_linear_transparent
      Merge pull request #23724 from dkurt:java_without_ant
      Merge pull request #23702 from dkurt:py_rotated_rect

Dmitry Matveev (3):
      G-API: Fix compilation error in Standalone mode
      Bump supported ONNX RT version to 1.14.1
      Merge pull request #23597 from dmatveev:dm/gapi_onnx_py_integration

Duong Dac (1):
      Merge pull request #20370 from ddacw:stub-gen-next

Fabrizio Di Vittorio (1):
      Merge pull request #23594 from fdivitto:fdivitto-traincascade-patch

Funatomi Takuya (1):
      Extend USAC coverage.

Gabriel Nascarella (1):
      Depthmap tutorial: add reference to class documentation and explain parameter usage

Gaotianhong (1):
      fix warning in pointPolygonTest

Genci Berisha (2):
      generateQR() method data loss fix
      Added QR_Code data flip support, flip and retry after first EEC failure

Giles Payne (3):
      Refactor Mat Converters and Mat QuickLook functionality to avoid "unrecognized selector" error
      Fix ocl::device::isIntel implementation
      Fix issue in Objective-C generator when a class name is a substring of its base class name

HAN Liutong (1):
      Fix HAL compatibility layer and modify use cases.

Ibai Gorordo (1):
      Merge pull request #23210 from ibaiGorordo:rect_nfa_bugfix

Ihsan Soydemir (1):
      Merge pull request #23128 from Isydmr:update-fastNlMeansDenoising-documentation

Jaakko Rantala (1):
      Update blenders.cpp

Jesus Noland (1):
      Add is after it to fix grammar mistake

Jindřich Šaršon (1):
      updated mac catalyst target to be compatible with latest xCode / macos

Kumataro (3):
      imgcodecs: update documentation for imwrite() to support images formats.
      remove tail whitespace
      Merge pull request #23433 from Kumataro:4.x-fix23416

Labib Asari (2):
      removed redundant code
      Merge pull request #23196 from labeeb-7z:printOptionInRoiSelector

Laurent Berger (2):
      Merge pull request #23442 from LaurentBerger:tuto_findFile
      Merge pull request #23555 from LaurentBerger:doc_format

Lilit Grigoryan (1):
      Fix focal length estimation from homography matrix

Lilo Huang (1):
      Merge pull request #23172 from lilohuang:master

Lukas Weber (1):
      add GraphCutSeamFinder

Maksim Shabunin (13):
      Backport C-API cleanup (imgproc) from 5.x
      RISC-V/RVV 0.7: v_add/v_sub saturation and avoiding 64-bit register in v_check_
      Fix some clang 14 warnings
      RISC-V: support RVV 0.7 in mainline RVV intrinsics
      cmake: fix V4L config verification conflict with OBSENSOR
      RISC-V: fix hardcoded options in RVV 0.7.1 toolchain file
      RISC-V: allow building scalable RVV support with GCC, LLVM 16 support
      Updated PGP key for security reports
      Merge pull request #23606 from mshabunin:fix-ffmpeg-packet-limit
      Merge pull request #23672 from mshabunin:fix-javadoc17
      imgproc/cvtColor: fixed invalid read in BGR2HLS
      Merge pull request #23666 from mshabunin:barcode-move
      objdetect: updated barcode test

Maksym Ivashechkin (1):
      Merge pull request #23078 from ivashmak:update_vsac

Matthias Möller (1):
      sets pixel info font colors based on current palette

Maxim Smolskiy (1):
      Fix function name in comment

Milan van Wouden (1):
      Fix typos in aruco_detector.hpp

Olivier Hotel (1):
      Addition of normalize_axis to ONNXImporter::parseSqueeze to support negative values for the axes attribut.

Onuralp Sezer (1):
      Merge pull request #23447 from onuralpszr:gradle80_namespace

Paul Kim (김형준) (1):
      Add `pthread.h` Inclusion if `HAVE_PTHREADS_PF` is defined

Peter Rekdal Khan-Sunde (1):
      Build fix

Pierre Chatelier (3):
      Merge pull request #13879 from chacha21:REDUCE_SUM2
      Merge pull request #23690 from chacha21:rotatedRectangleIntersection_precision
      Merge pull request #22947 from chacha21:hasNonZero

Prasanth R (1):
      #21804 Add opencv_gapi as dep to samples/cpp

Rahul Noronha (1):
      Update properties - typo

Raj Kachhadiya (1):
      Update py_intro.markdown

Rostislav Vasilikhin (3):
      cvIsInf(double) fix + regression test
      Merge pull request #23025 from savuor:backport3_stddev_calib_fix
      Merge pull request #23179 from savuor:port34_stddev_calib_fisheye

Sajjad Ali (1):
      fix "ImportError: DLL load failed while importing cv2" while installing using pre-built binaries

Sean McBride (5):
      Fixed undefined left shifting of negative number
      Merge pull request #23055 from seanm:sprintf2
      Deprecated convertTypeStr and made new variant that also takes the buffer size
      Use std::atomic<bool> as it's necessary for correct thread safety
      Fixed UBSan warning about undefined pointer arithmetic overflow

Sergey Petrenko (1):
      check keydown event characters length before returning the pressed character code

Simon Lynen (1):
      Make LineSegmentDetector deterministic by using stable_sort for ordering keypoints prior to region growing

SoY Szala (1):
      Proposed solution for issue #23633

Spike (1):
      Fix reference counting errors in registerNewType

Stefan Becker (2):
      Aruco/Charuco test case fixes for floating point for loops
      ChArUco pre460 pattern support

Tinson Lai (1):
      Change custom_hal.hpp output location

TolyaTalamanov (6):
      Handle meta for multiple infer inputs
      Handle const inputs descs in giebackend
      Compilation fix
      Change logic for applying resize
      Fix ifdef condition
      Apply ov::Core WA

Tomoaki Teshima (2):
      make test tolerate to rounding error
      suppress warning

TuNanTang (2):
      Merge pull request #23341 from TuNanTang:3.4
      Optimize&Fix fitEllipse sample

Ulvi YELEN (1):
      if browser supports wasm but only asm.js path provided use asm.js as fallback

Vaclav Vavra (1):
      different interpolation by double image (#23124)

Vadim Levin (10):
      feat: named arguments handling in Python interface
      fix: remove extra '/O' modifier for '/IO' arguments
      feat: provide cv2.typing aliases at runtime
      feat: manual refinement for Python API definition
      feat: re-export symbols to cv2 level
      fix: typing module enums references
      feat: add OpenCV error class to cv2/__init__.pyi
      Merge pull request #23816 from VadimLevin:dev/vlevin/export-all-caps-enum-constants
      fix: AST nodes required usage imports
      fix: conditionally define generic NumPy NDArray alias

Vadim Pisarevsky (2):
      temporarily set "enable_precise_upscale=false" by default to avoid sporadic failures in regression tests (#23270)
      fixed another SIFT constructor (#23272)

Vincent Rabaud (3):
      Merge pull request #22441 from vrabaud:hls_while
      Merge pull request #23596 from vrabaud:libavif
      Merge pull request #24274 from vrabaud:webp_1.3.2

Vladimir Ponomarev (6):
      Remove separator between trackbars.
      Merge pull request #23276 from vovka643:flann_corrections
      Merge pull request #23486 from vovka643:4.x_calibration_with_aruco
      Merge pull request #23587 from vovka643:4.x_aruco_calibrate_py
      Merge pull request #23363 from vovka643:4.x_generate_charuco
      Merge pull request #23575 from vovka643:4.x_aruco_calib3d_calibration

WU Jia (1):
      Merge pull request #23531 from kaingwade:orbbec_python_sample

Wang Kai (3):
      fixing typo
      fixing typo of a variable name in dnn::runFastConv
      removing unreachable code and fixing a typo

Wwupup (1):
      upgrade FaceDetectorYN to v2

Xxfore (1):
      Merge pull request #22938 from Xxfore:4.x

Yang Chao (1):
      Open CV_CPU_NEON_DOTPROD on Apple silicon devices

Yannis Guyon (2):
      Avoid double-checked locking with TSAN in parallel
      Merge pull request #23131 from y-guyon:align_ptr_intrin_sse

Yuantao Feng (11):
      Merge pull request #23095 from fengyuentau:fix_omp_macos
      Merge pull request #23047 from fengyuentau:layer_norm
      Merge pull request #23219 from fengyuentau:add_gelu
      Merge pull request #23319 from fengyuentau:fix_zoo_issue_136
      Merge pull request #23296 from fengyuentau:fix_identifying_constant
      Merge pull request #23476 from fengyuentau:add_note_for_yunet
      Merge pull request #23401 from fengyuentau:fix_cann_layer_support
      dnn: refactor reduce (#23613)
      Merge pull request #23655 from fengyuentau:qlinearsoftmax
      Merge pull request #23829 from fengyuentau:fixes4orbbec
      Merge pull request #23853 from fengyuentau:disable_fp16_warning

Zero-nnkn (1):
      Fix error of `POSE_PAIRS` in pose estimation doc

Zero2key (1):
      add opencv.js imread function can use OffscreenCanvas

Zhi-Qiang Zhou (1):
      Update region_layer.cpp

Zihao Mu (7):
      Merge pull request #23255 from zihaomu:fused_cuda_naryeltwise
      Merge pull request #23192 from zihaomu:clean_up_SIMD_code
      Merge pull request #22750 from zihaomu:improve_blobFromImage
      Merge pull request #22275 from zihaomu:fp16_support_conv
      speed up vulkan dnn, and support ios and apple m1 chip. (#23349)
      Merge pull request #23763 from zihaomu:add_runtime_check
      Merge pull request #23952 from zihaomu:fix_depth_conv_5x5

Zwyx (1):
      Switch `rows` and `cols` in call to Mat.zeros

anders-nylander (1):
      Merge pull request #21736 from anders-nylander:fix_android_sdk_tools_dependency

anderskiaer (1):
      Add possibility for disabling inlining `wasm` in `opencv.js`

captain-n3m0 (1):
      Fixed matchTemplate function. #23585

cudawarped (6):
      cuda: add ada lovelace and hopper cuda arch
      core: define cuda test size with row/col of 1
      VideoCapture: apply bitstream filter to all h264/5 raw streams
      Videoio: FFMpeg remove locks if OPENCV_FFMPEG_IS_THREAD_SAFE==true
      cuda: add python bindings to allow GpuMat and Stream objects to be initialized from raw pointers
      cv::VideoCapture: change CAP_PROP_FOURCC to prefer codec_id over codec_tag

dizcza (1):
      [opencv 3.x] back-ported tbb support ubuntu 22.04

eplankin (1):
      Merge pull request #23443 from eplankin:3.4

fengyuentau (3):
      support broadcast on axis > 1 for Expand
      allow null constant_value in Pad and ignore it when loading
      fix overflow

gottagofaster236 (2):
      Fix OBS Virtual Camera capture.
      Use NV12 instead of YUY2 for OBS Virtual Camera.

hzcyf (1):
      add support for Orbbec Femto Mega RGB-D camera

inayd (1):
      Fix occuring artifacts in fillPoly

ippei.i (1):
      Merge pull request #23300 from ippei-i:CAP_PROP_AUTO_WB-and-CAP_PROP_WHITE_BALANCE_BLUE_U_support_in_CAP_DSHOW

kallaballa (1):
      Log a debug message if a capture backend is generally available but isn't capabable of a capture mode.

keith siilats (3):
      Update charuco_detector.cpp
      Merge pull request #23436 from siilats:patch-2
      Update aruco_detect_board_charuco.py

lamm45 (1):
      Merge pull request #22798 from lamm45:distransform-large

n0099 (1):
      Merge pull request #23342 from n0099:#23335

smeng9 (2):
      fix typo: stetDictionary to setDictionary
      Fix skipped corner refinment branching logic

souch (1):
      Merge pull request #23417 from souch:souch-fix-parallel-backend-example

tantei3 (1):
      Merge pull request #23446 from tantei3:bmp_fix

thewoz (1):
      Merge pull request #23394 from thewoz:Cocoa-Scroll-Wheel

tingbo.liao (1):
      Fix bugs of test case failure

tkram01 (1):
      Fix for using sampleIdx to limit training data

triple Mu (1):
      Update setup.py

unknown (7):
      te for MSMF in doc
      use findFile in opengl.cpp sample
      Typo in enum cv::QuatEnum::EulerAnglesType
      remove unused var
      solve Issue I23683
      solve Issue 23685
      checktype in blobFromImages and blobFromImagesWithParams

vovka643 (3):
      Define charuco board parameters with command line
      Added depricated_backends list. Added new information masseges. It needs to inform user, when he tries to use depricated or not uses backend
      added aruco pattern into stereo_calibration.cpp

wanli (5):
      make GEMM can be supported with transA and transB in CUDA
      release MUL and ADD operator on CUDA
      make 'abcd op 1b11' broadcast support cuda
      fix nary elementwise bug in cpu
      Solve the bug of same shape broadcast with CUDA

whuaegeansea (1):
      Fix bug

zihaomu (14):
      fix possible segmentation fault error in winograd on x86
      add depthwise add fuse
      fix depth wise issue.
      move global skip out of if loop, and add opencv_deny_list
      fix bug in layer fusion
      fix bug in 32 bit cpu
      support the split node of onnx opset >= 13
      fix the bug, disable the fast1x1 when padding is not 0.
      add scale factor to DB demo.
      add broadcast where node
      remove flag of convolution
      add the node from ci-gha
      when stride ==0, it should be bug
      remove unsupported unsupported unicode